# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false
command_timeout = 5000

format = """
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$cmd_duration\
$status\
$character\
"""

right_format = """$time"""

[git_branch]
format = "❯ [$branch(:$remote_branch)]($style) "

[git_status]
format = '[$ahead_behind$all_status]($style)'
conflicted = '[ $count](red) '
ahead = ' $count '
behind = ' $count '
diverged = ' ${ahead_count}  ${behind_count} '
untracked = '[ $count](blue) '
stashed = ' $count '
modified = '[ $count](#FFFF00) '
staged = ' $count '
renamed = '[󰛿 $count](#FFFF00) '
deleted = '[ $count](red) '
style = 'green'

[time]
disabled = false
format = "[$time](style)"

[status]
pipestatus_format = "[❯ $symbol$pipestatus]($style) "
pipestatus_segment_format = "[$int]($style)"
format = "[❯ $symbol$int]($style) "
pipestatus = true
disabled = false
symbol = "✘"

[line_break]
disabled = true

[cmd_duration]
format = "[❯ $duration]($style) "
style = "yellow bold"
